### ISSUE TITLE
[bug] header Height not updated once built

### ISSUE THREAD

**Issue by hassanbasanjide** [fluttercommunity/backdrop#40] opened 2020-06-28 13:41 UTC
if i change the height of Header by BLOC  and set it dynamic  the header Height  nothing 
 changed.

**Comment by WieFel** [comment] 2020-06-28 15:03
Could you provide a simple code snippet with what you are trying to achieve?

Why do you need to change the height dynamically via BLOC?
Maybe you should have a look at the `stickyFrontLayer` property, which allows to automatically adapt the height to the back layer content.

**Comment by daadu** [comment] 2020-06-28 15:52
@hassanbasanjide It could be because of flutter not redrawing the `BackdropScaffold`. Does setting `UniqueKey` to `BackdropScaffold` solve the issue? 

As @WieFel suggested, share some code that could reproduce the bug.

**Comment by hassanbasanjide** [comment] 2020-06-29 08:12
@WieFel  
class StoreSubScreen extends StatefulWidget {
  @override
  _StoreSubScreenState createState() => _StoreSubScreenState();
}

class _StoreSubScreenState extends State<StoreSubScreen>
    with TickerProviderStateMixin {
  String get store2 => null;
  AnimationController _controller;
  bool expanded = false;
  @override
  void initState() {
    _controller = AnimationController(
      reverseDuration: const Duration(milliseconds: 500),
      vsync: this,
      duration: const Duration(milliseconds: 500),
      value: 1,
    );

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    @override
    void changeController() {

      setState(() {
        expanded ? _controller.forward() : _controller.reverse();
        expanded = !expanded;
    
      });
    }

    return BlocBuilder<StoreBackDropControllerBloc,
        StoreBackDropControllerState>(
      builder: (context, state) {
        return BackdropScaffold(
         stickyFrontLayer: true,
          resizeToAvoidBottomInset: false,
          appBar: state.when(
            initial: (state) => storeNormalAppBar(
              context: context,
              targetFunction: () => changeController(),
            ),
            searchPage: (state) => searchAppBar(
              context: context,
              targetFunction: () => changeController(),
            ),
            filterPage: (state) => filterAppBar(
              context: context,
              targetFunction: () => changeController(),
            ),
          ),
          frontLayer: StorePageSubScreenForm(),
          subHeaderAlwaysActive: false,
      
          frontLayerBorderRadius: BorderRadius.circular(0),
          controller: _controller,
          backLayer: state.when(
              initial: (state) => SearchScreen(),
              searchPage: (state) => SearchScreen(),
              filterPage: (state) => FiltersScreen()),
          
        );
      },
    );
  }
}

**Comment by hassanbasanjide** [comment] 2020-06-29 08:21
@WieFel   stickyfrontlayer is true. and backlayers have a different height but nothing Changed.  ;(
the space of back layer witch have no content is blue.
actually the header height just accept one height at begin.
  @override
  Widget build(BuildContext context) {
    @override
    void changeController() {

      setState(() {
        expanded ? _controller.forward() : _controller.reverse();
        expanded = !expanded;
    
      });
    }

    return BlocBuilder<StoreBackDropControllerBloc,
        StoreBackDropControllerState>(
      builder: (context, state) {
        return BackdropScaffold(
         stickyFrontLayer: true,
          resizeToAvoidBottomInset: false,
          appBar: state.when(
            initial: (state) => storeNormalAppBar(
              context: context,
              targetFunction: () => changeController(),
            ),
            searchPage: (state) => searchAppBar(
              context: context,
              targetFunction: () => changeController(),
            ),
            filterPage: (state) => filterAppBar(
              context: context,
              targetFunction: () => changeController(),
            ),
          ),
          frontLayer: StorePageSubScreenForm(),
          subHeaderAlwaysActive: false,
      
          frontLayerBorderRadius: BorderRadius.circular(0),
          controller: _controller,
          backLayer: state.when(
              initial: (state) => SearchScreen(),
              searchPage: (state) => SearchScreen(),
              filterPage: (state) => FiltersScreen()),
          
        );
      },
    );
  }
}

**Comment by hassanbasanjide** [comment] 2020-06-29 08:25
![Screenshot (9)](https://user-images.githubusercontent.com/58950648/85990689-a4c2f900-ba07-11ea-94b3-34b61007e6fd.png)
![Screenshot (8)](https://user-images.githubusercontent.com/58950648/85990697-a7bde980-ba07-11ea-93ad-542243585b75.png)

**Comment by hassanbasanjide** [comment] 2020-06-29 08:30
@daadu   i need some things like images.  now what is your recommend?

**Comment by hassanbasanjide** [comment] 2020-07-01 15:07
The problem is you can't change the key which is created for the backdrop. And because of that when the backdrop changes in any state, the widget isn't being recreated and the height of the widget is not being redrawn. @daadu I can't set a new UniqueKey upon changing state because the BackdropScaffold doesn't accepts Key. And if I change the parent's key when the state changes It the backLayer Isn't being drawn.

**Comment by daadu** [comment] 2020-07-01 17:21
@hassanbasanjide I will look into this during weekend.

**Comment by WieFel** [comment] 2020-07-18 14:56
@hassanbasanjide I had a look at it but it is still not enough code for me to reproduce the issue completely.
I pushed a version of `BackdropScaffold` containing the `key` property to the branch [scaffold_key](https://github.com/fluttercommunity/backdrop/tree/scaffold_key).

You can try to import it into your project like so (in your `pubspec.yaml`):
```dart
dependencies:
  backdrop:
    git:
      url: git@github.com:fluttercommunity/backdrop.git
      ref: scaffold_key
```
Try setting a key on `BackdropScaffold` and tell us if that solves your problem. If yes, we can apply the changes to the master channel of backdrop.

**Comment by hassanbasanjide** [comment] 2020-08-12 12:20
@WieFel Thank you I will look at this but I'm looking forward to see this in production

**Comment by WieFel** [comment] 2020-08-12 12:23
@hassanbasanjide let un know if it works

**Comment by amebrahimi** [comment] 2020-09-12 08:27
@WieFel I want to use this
```
dependencies:
  backdrop:
    git:
      url: git@github.com:fluttercommunity/backdrop.git
      ref: scaffold_key
```
but I can't is there any permissions you have to give or something?

**Comment by WieFel** [comment] 2020-09-13 08:01
>       url: git@github.com:fluttercommunity/backdrop.git

Maybe try `url: https://github.com/fluttercommunity/backdrop.git`

Does that work?

**Comment by proninyaroslav** [comment] 2020-09-16 08:30
@daadu 
I faced a similar problem. Calling `setState` changes the height of the widget, but this doesn't affect the height of the back layer, it stays the same. I also tried the `scaffold_key` branch, but it has similar behavior.

```Dart
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String text = "Back Layer 1";
  double height = 100;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Backdrop Example",
      theme: ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: BackdropScaffold(
        appBar: BackdropAppBar(
          title: Text("Backdrop Example"),
          stickyFrontLayer: true,
          actions: <Widget>[
           LayoutBuilder(
              builder: (context, constraints) => IconButton(
                icon: Icon(Icons.terrain),
                onPressed: () {
                  setState(() {
                    height = 200;
                    text = "Back layer 2";
                    Backdrop.of(context).fling();
                  });
                },
              ),
            ),
          ],
        ),
        backLayer: Container(
          height: height,
          child: Center(child: Text(text)),
        ),
        frontLayer: Center(
          child: Text("Front Layer"),
        ),
      ),
    );
  }
}
```

**Comment by proninyaroslav** [comment] 2020-09-16 08:35
![backdrop](https://user-images.githubusercontent.com/7840559/93313127-b77fe980-f810-11ea-8d91-ae56ec0e8634.gif)

**Comment by WieFel** [comment] 2020-09-16 09:28
@proninyaroslav thanks for the code example.

The problem is that changing the height of the back layer only affects the back layer itself and its children. The problem here is that `BackdropScaffold` (which is the parent of back layer) isn't updated, not even using the `scaffold_key` branch.
The original idea was that the back layer would keep its height always the same.

@daadu to solve the problem we could add a callback `updateBackLayerHeight()` to `BackdropScaffold` which could be called if the height of the back layer changes. What do you think?

**Comment by proninyaroslav** [comment] 2020-09-16 09:46
@WieFel 
Thank you for response. Is there a workaround for now? I would like to use a backdrop in app, like a hybrid of Navigation Drawable + Top Sheet (this concept is in the official guideline).

**Comment by WieFel** [comment] 2020-09-16 12:09
I will have a look asap and provide you with a feature branch you can use meanwhile...

**Comment by daadu** [comment] 2020-09-16 12:49
@WieFel `updateBackLayerHeight` idea seems like a workaround.

Proper fix would be to not set `headerHeight` etc, on `initState` and do it instead in `build` itself, I am working on this. Meanwhile you can provide with the workaround to @proninyaroslav

**Comment by daadu** [comment] 2020-09-16 13:36
I am worked on the fix in branch `fix/stickyHeaderWhenBackLayerUpdated`

@proninyaroslav @amebrahimi Please test the fix by pointing to this branch in `pubspec.yaml`


@WieFel Can you also test this changes against demo app? And I don't think we need to go for workaround now!

**Comment by daadu** [comment] 2020-09-16 13:47
> Thank you for response. Is there a workaround for now? I would like to use a backdrop in app, like a hybrid of Navigation Drawable + Top Sheet (this concept is in the official guideline).

@proninyaroslav Once this is fixed, can you work on adding this use case  to the demo app (flutter app to demonstrate all use cases in MDG for backdrop), it is under `demo/` dir?

Or @WieFel have we already covered it?

@proninyaroslav Can you post the screenshot form MDG that explains this use case?

**Comment by daadu** [comment] 2020-09-16 13:50
@hassanbasanjide Sorry, for being 2 months late. The problem only got clear when @proninyaroslav posted a reproduceable code.

**Comment by proninyaroslav** [comment] 2020-09-16 14:19
@daadu 
Yes, now it works as expected. Thank you.

> Once this is fixed, can you work on adding this use case to the demo app (flutter app to demonstrate all use cases in MDG for backdrop), it is under `demo/` dir?

Ok, let me know.

**Comment by WieFel** [comment] 2020-09-16 15:49
> Or @WieFel have we already covered it?

Well there is no specific use case for targeting a changing back layer height in the material design guidelines.
Not sure if we should add this as separate use case to demo app. In my opinion the dynamic height of the back layer is actually a feature that one would already expect from this package...

**Comment by proninyaroslav** [comment] 2020-09-16 15:57
@WieFel 
This is mentioned here, in the "Revealing the back layer" section https://material.io/components/backdrop#behavior
> The height of the back layer is based on the size of its content.

![ezgif com-resize](https://user-images.githubusercontent.com/7840559/93362223-67c01300-f84e-11ea-9a37-e68e06cdeb8b.gif)

**Comment by proninyaroslav** [comment] 2020-09-16 18:23
@daadu @WieFel 
Is it possible to animate the transition between the back layers when one of the layers is already revealed? In other words, moving to a second back layer with a different height makes the front layer lower/upper, but without any animation.

![ezgif-5-bc3289b2be3a](https://user-images.githubusercontent.com/7840559/93376672-98aa4300-f862-11ea-83eb-05c11d975de2.gif)

```Dart
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String text = "Back Layer 1";
  double height = 100;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Backdrop Example",
      theme: ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: BackdropScaffold(
        appBar: BackdropAppBar(
          title: Text("Backdrop Example"),
          actions: <Widget>[
           LayoutBuilder(
              builder: (context, constraints) => IconButton(
                icon: Icon(Icons.terrain),
                onPressed: () {
                  setState(() {
                    height = 200;
                    text = "Back layer 2";
                  });
                },
              ),
            ),
          ],
        ),
        stickyFrontLayer: true,
        backLayer: Container(
          height: height,
          child: Center(child: Text(text)),
        ),
        frontLayer: Center(
          child: Text("Front Layer"),
        ),
      ),
    );
  }
}
```

**Comment by daadu** [comment] 2020-09-16 18:39
This fix has landed in [`v0.4.5` on pub.dev](https://pub.dev/packages/backdrop/versions/0.4.5)

@hassanbasanjide @proninyaroslav  Check yourself on repo and pub README!!

**Comment by hassanbasanjide** [comment] 2020-09-18 07:08
@daadu   thank you for your response. ;)

**Comment by daadu** [comment] 2020-09-18 13:11
> @daadu @WieFel
> Is it possible to animate the transition between the back layers (size changing) when one of the layers is already revealed? In other words, moving to a second back layer with a different height makes the front layer lower/upper, but without any animation.


@proninyaroslav Use `AnimatedSize` widget around `backLayer`

**Comment by daadu** [comment] 2020-09-19 05:00
@proninyaroslav Can you raise this as a new issue? I think this should be resolved. What about you @WieFel ?

**Comment by daadu** [comment] 2020-09-19 05:32
This is working:

```dart
backLayer: NotificationListener<SizeChangedLayoutNotification>(
          onNotification: (notification) {
            SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
              setState(() {});
            });
            return true;
          },
          child: SizeChangedLayoutNotifier(
            child: AnimatedSize(
              vsync: this,
              duration: Duration(milliseconds: 200),
              child: Container(
                height: height,
                child: Center(child: Text(text)),
              ),
            ),
          ),
        ),
```

**Comment by daadu** [comment] 2020-09-19 05:33
The issue was that `_MeasureSize` is notifying size change

**Comment by daadu** [comment] 2020-09-19 05:34
The issue is `_MeasureSize` is notifying sizeChange only at start of animation. I think using `SizeChangedLayoutNotifier` inside `_MesureSize` should work out of the box.

**Comment by daadu** [comment] 2020-09-19 05:46
Closing this issue, this issue will be further tracked at #55

**Closed by daadu** 2020-09-19 05:46 UTC
Labels: bug, question
