### ISSUE TITLE
when App is using full screen it leaves the space at bottom for buttons

### ISSUE THREAD

**Issue by amanv8060** [fluttercommunity/backdrop#15] opened 2020-05-14 18:55 UTC
please see

**Comment by daadu** [comment] 2020-05-15 05:52
Could you give some snippet to reproduce the bug with screenshots, for more clarity?

**Comment by amanv8060** [comment] 2020-05-15 21:34
Sure ! 
It leaves the Space dedicated for buttons, 
i could hide it by putting a bottom nav bar there
![Screenshot_1589578333](https://user-images.githubusercontent.com/33422449/82098032-c4d17e00-9721-11ea-918f-efae0dd9d9c6.png)
![Screenshot_1589578346](https://user-images.githubusercontent.com/33422449/82098035-c69b4180-9721-11ea-9770-36ed5c505b1f.png)

**Comment by daadu** [comment] 2020-05-16 06:50
@amanv8060 I need the code that produces this output to debug. Can you provide a minimum code snippet to produce this error?

**Comment by amanv8060** [comment] 2020-05-16 08:49
a very simple method to reproduce
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:backdrop/backdrop.dart';

void main() {
  runApp(MyApp());
  SystemChrome.setEnabledSystemUIOverlays([]);
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home:BackdropScaffold(
        backLayer: ListView(
          children: <Widget>[
            Text("HEy")
          ],
        ),
        frontLayer: Text("hey"),
      ),
    );
  }
}

```

**Comment by WieFel** [comment] 2020-05-16 09:18
I just tried to reproduce the problem using your code, but on my emulator (running Android 10) I cannot reproduce it. It seems to work fine there.
<img alt="Screenshot_1589620194" src="https://user-images.githubusercontent.com/8345062/82115883-ea807680-9765-11ea-81fa-50ce0849f057.png" width="250"/>  <img alt="Screenshot_1589620198" src="https://user-images.githubusercontent.com/8345062/82115884-eb190d00-9765-11ea-9fa5-5bb3f14f33f0.png" width="250"/>

I am using Flutter Channel stable, v1.17.1.

Could you provide the output of
```
flutter doctor
```
please?
Maybe you are using an old version of flutter...

**Comment by amanv8060** [comment] 2020-05-16 13:53
```
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_IN)
    • Flutter version 1.17.1 at /home/aman/Android/flutter
    • Framework revision f7a6a7906b (4 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/aman/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/aman/Desktop/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/aman/Desktop/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API
      29) (emulator)

```

**Comment by WieFel** [comment] 2020-05-17 08:22
This is a little strange.
If I execute your code snippet within the (project-intern) example app of backdrop, the problem doesn't show up.
But adding the snippet to a new empty flutter app does reproduce the problem.

At the moment I don't know what causes the problem. I suppose that it might be caused by the dynamic height calculation within backdrop. I have to look into this more in-depth.

@daadu maybe you have an idea?

**Comment by amanv8060** [comment] 2020-05-17 08:26
A nice way to avoid it is to have this backdrop scaffold as a child of scaffold having a bottom nav bar

**Comment by daadu** [comment] 2020-09-10 09:21
@amanv8060 We have added all `Scaffold` properties (including `bottomNavigationBar`) to `BackdropScaffold` in `v0.4.4`. Please check if that solves the issue.

**Comment by amanv8060** [comment] 2020-09-28 09:17
@daadu , it got missed  , i will try and if the problem has been solved , i will close this .

**Comment by daadu** [comment] 2021-03-02 10:53
Closing this issue, since stalled.
 
Feel free to request re-opening.

**Closed by daadu** 2021-03-02 10:53 UTC
Labels: bug, question
