### ISSUE TITLE
Only expand as much as needed to reveal the back layer

### ISSUE THREAD

**Issue by heath3n** [fluttercommunity/backdrop#35] opened 2020-06-04 18:50 UTC
Currently the back layer expands fully; it should only expand as much as needed to fully show its contents.

**Comment by WieFel** [comment] 2020-06-04 19:09
This is implemented by the property `stickyFrontLayer` which defaults to `false`. You can set it to `true` and it will adapt to the back layer's height.
```dart
BackdropScaffold(
    appBar: BackdropAppBar(
        title: Text("Backdrop Example"),
        actions: <Widget>[
        BackdropToggleButton(
            icon: AnimatedIcons.list_view,
        )
        ],
    ),
    backLayer: Container(
        height: 200.0,
        child: Center(child: Text("Back Layer")),
    ),
    frontLayer: Center(
        child: Text("Front Layer"),
    ),
    stickyFrontLayer: true,
)
```

**Comment by daadu** [comment] 2020-06-05 08:32
@heath3n This only works if the height of the back layer widget is bounded. If you are using `ListView` or something similar set `shrinkWrap` to `true`

**Comment by PembaTamang** [comment] 2020-09-05 15:07
@daadu using a ListView and shrinkWrap did not work for me. What else can I do?

**Comment by daadu** [comment] 2020-09-06 07:14
@PembaTamang Please provide us with minimum code that can reproduce the issue. We will look into it.

**Comment by amanv8060** [comment] 2020-09-08 09:39
```
class BackLayer extends StatefulWidget {
  @override
  _BackLayerState createState() => _BackLayerState();
}

class _BackLayerState extends State<BackLayer> {
  @override
  Widget build(BuildContext context) {
    return Container(

      color:  Color(0xFFE7305b),
      child: ListView(
        shrinkWrap: true,
        children:  <Widget>[
ListTile(title:Text("hey")),
ListTile(title:Text("hey")),
ListTile(title:Text("hey")),
ListTile(title:Text("hey")),
         
        ],
      ),
    );
  }
}
```
use this as Your Backlayer
and dont give header height

**Comment by WieFel** [comment] 2020-09-08 13:28
I could not reproduce the problem. For me it works fine using your BackLayer and `stickyFrontLayer: true`.
Maybe take a look at https://github.com/fluttercommunity/backdrop/blob/b547c82135dff6ade44473af54a861d513e087ac/lib/navigation.dart#L72-L87 which implements basically the same thing.

Which flutter channel are you using and do you use the newest version of it?

**Comment by daadu** [comment] 2020-09-09 06:49
@amanv8060 Just to confirm, did you set `stickyFrontLayer` to `true` for `BackdropScaffold`?

**Comment by amanv8060** [comment] 2020-09-09 07:17
> @amanv8060 Just to confirm, did you set `stickyFrontLayer` to `true` for `BackdropScaffold`?

this was causing issue . Close this , if the issue author has no problem

**Closed** 2020-09-09 08:21 UTC
Labels: question
